language: scala
sudo: false
cache:
  directories:
  - "$HOME/.ivy2"
matrix:
  include:
  - jdk: openjdk8
    scala: 2.11.12
    env: SPARK_VERSION="2.4.0-SNAPSHOT" INTEGRATION_TESTS="true"
script:
- "./dev/run-tests-travis.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- openssl aes-256-cbc -K $encrypted_3e088c9f7248_key -iv $encrypted_3e088c9f7248_iv
  -in snowflake.travis.conf.enc -out snowflake.travis.conf -d
