version: '3'

services:
  master:
    image: $DOCKER_IMAGE_TAG
    command: master
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - SNOWFLAKE_TEST_CONFIG_SECRET=$SNOWFLAKE_TEST_CONFIG_SECRET
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080

  worker_1:
    image: $DOCKER_IMAGE_TAG
    command: worker spark://master:7077
    depends_on:
      - master
    ports:
      - 8081:8081
      - 18081:18081
    environment:
      - SNOWFLAKE_TEST_CONFIG_SECRET=$SNOWFLAKE_TEST_CONFIG_SECRET
      - SPARK_WORKER_PORT=18081
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_MEMORY=1300m
      - SPARK_WORKER_CORES=2

  worker_2:
    image: $DOCKER_IMAGE_TAG
    command: worker spark://master:7077
    depends_on:
      - master
    ports:
      - 8082:8082
      - 18082:18082
    environment:
      - SNOWFLAKE_TEST_CONFIG_SECRET=$SNOWFLAKE_TEST_CONFIG_SECRET
      - SPARK_WORKER_PORT=18082
      - SPARK_WORKER_WEBUI_PORT=8082
      - SPARK_WORKER_MEMORY=1300m
      - SPARK_WORKER_CORES=2

  worker_3:
    image: $DOCKER_IMAGE_TAG
    command: worker spark://master:7077
    depends_on:
      - master
    ports:
      - 8083:8083
      - 18083:18083
    environment:
      - SNOWFLAKE_TEST_CONFIG_SECRET=$SNOWFLAKE_TEST_CONFIG_SECRET
      - SPARK_WORKER_PORT=18083
      - SPARK_WORKER_WEBUI_PORT=8083
      - SPARK_WORKER_MEMORY=1300m
      - SPARK_WORKER_CORES=2

  worker_4:
    image: $DOCKER_IMAGE_TAG
    command: worker spark://master:7077
    depends_on:
      - master
    ports:
      - 8084:8084
      - 18084:18084
    environment:
      - SNOWFLAKE_TEST_CONFIG_SECRET=$SNOWFLAKE_TEST_CONFIG_SECRET
      - SPARK_WORKER_PORT=18084
      - SPARK_WORKER_WEBUI_PORT=8084
      - SPARK_WORKER_MEMORY=1300m
      - SPARK_WORKER_CORES=2

  worker_5:
    image: $DOCKER_IMAGE_TAG
    command: worker spark://master:7077
    depends_on:
      - master
    ports:
      - 8085:8085
      - 18085:18085
    environment:
      - SNOWFLAKE_TEST_CONFIG_SECRET=$SNOWFLAKE_TEST_CONFIG_SECRET
      - SPARK_WORKER_PORT=18085
      - SPARK_WORKER_WEBUI_PORT=8085
      - SPARK_WORKER_MEMORY=1300m
      - SPARK_WORKER_CORES=2

  testdriver:
    image: $DOCKER_IMAGE_TAG
    # Run test.
    command: runtest
    depends_on:
      - master
      - worker_1
      - worker_2
    environment:
      - SNOWFLAKE_TEST_CONFIG_SECRET=$SNOWFLAKE_TEST_CONFIG_SECRET
      - SNOWFLAKE_TEST_ACCOUNT=aws
      - GITHUB_SHA=$GITHUB_SHA
      - GITHUB_RUN_ID=$GITHUB_RUN_ID
      - TEST_SPARK_CONNECTOR_VERSION=$TEST_SPARK_CONNECTOR_VERSION
      - TEST_SCALA_VERSION=$TEST_SCALA_VERSION
      - TEST_COMPILE_SCALA_VERSION=$TEST_COMPILE_SCALA_VERSION
      - TEST_JDBC_VERSION=$TEST_JDBC_VERSION
      - TEST_SPARK_VERSION=$TEST_SPARK_VERSION
